# Generated by Django 4.2.3 on 2023-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_prescription_prescribed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
