# Generated by Django 4.2.3 on 2023-07-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appointment_id_alter_prescription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ofdoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ofpatient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.patient'),
        ),
    ]
